Hi @marcomusy, 
The environment was built using the versions of vedo that are in conda-forge. Informacion about the version and build is next:

> 
> packages in environment at D:\Applications\Miniconda\envs\mHpy39_v2:
> Name - Version - Build  Channel
> vedo - 2023.4.3 - pyhd8ed1ab_0 - conda-forge
> vmtk - 1.5.0 - py39hcda1aa6_9 - conda-forge
> vtk - 9.1.0 - qt_py39hca7f291_215 - conda-forge

Is it possible that the conda-forge version I have installed is different to the one you are currently testing this on? 
I bumped into another error that I am not being able to solve.
I am running the code using spyder and there is some weird behaviour happening when using the function 